spring:
  application:
    name: todo-list
  datasource:
    url: ${POSTGRES_URI}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    driver-class-name: org.postgresql.Driver
  config:
    import: file:misc/.env[.properties]
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    template:
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 1000ms
        multiplier: 2.0
        max-interval: 5000ms

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  issuer: ${JWT_ISSUER}